### ISSUE TITLE
Plum Switch Not Appearing In Site Map

### ISSUE THREAD

**Issue by robertjackson17** [mikenemat/org.openhab.binding.plum#1]
I am setting up openHAB 1.8.2 and trying to integrate my Plum switches.

I seem to have about half of the Plum integration working. I found the tokens with the plum-probe.

I have set up a plum switch in .items: Dimmer Plum_Kitchen_Island_Dimmer "Plum_Kitchen_Island_Dimmer [%d]" {plum="192.168.1.111:e68239c7-a43a-4adb-a1ce-2edfe9e0adb0#dimmer"} Switch Plum_Kitchen_Island_Switch "Plum Kitchen Island Switch" {plum="192.168.1.111:e68239c7-a43a-4adb-a1ce-2edfe9e0adb0#switch"} Number Plum_Kitchen_Island_Switch_powerMeter "Plum_Kitchen_Island_Switch_powerMeter [%d W]" {plum="192.168.1.111:e68239c7-a43a-4adb-a1ce-2edfe9e0adb0#powermeter"}

The log file suggests things are being recognized: 2016-05-07 20:38:13.682 [INFO ] [b.p.PlumGenericBindingProvider] - processing item "Plum_Kitchen_Island_Dimmer" read from .items file with cfg string 192.168.1.111:e68239c7-a43a-4adb-a1ce-2edfe9e0adb0#dimmer 2016-05-07 20:38:13.683 [INFO ] [b.p.PlumGenericBindingProvider] - processing item "Plum_Kitchen_Island_Switch" read from .items file with cfg string 192.168.1.111:e68239c7-a43a-4adb-a1ce-2edfe9e0adb0#switch 2016-05-07 20:38:13.684 [INFO ] [b.p.PlumGenericBindingProvider] - processing item "Plum_Kitchen_Island_Switch_powerMeter" read from .items file with cfg string 192.168.1.111:e68239c7-a43a-4adb-a1ce-2edfe9e0adb0#powermeter 2016-05-07 20:38:13.713 [INFO ] [.o.b.p.i.PlumTCPStreamListener] - Starting monitor thread for Plum IP: 192.168.1.111 2016-05-07 20:39:19.076 [INFO ] [binding.plum.PlumActiveBinding] - Polling Plum HTTP 192.168.1.111 2016-05-07 20:39:19.904 [INFO ] [binding.plum.PlumActiveBinding] - Plum HTTP Request to IP 192.168.1.111 returned: HTTP/1.1 200 OK

Then I get stuck.

I've added to the .sitemap:
Switch Plum_Kitchen_Island_Switch
but the switch never appears in the browser interface.

I'd certainly appreciate any guidance you can offer. Bear in mind that I'm new to openHAB so I might very well be doing something wrong. FWIW, I was able to get Hue and Wemo working before tackling Plum.

Thank you,
Rob

**Comment by robertjackson17** [comment]
After playing with it some more, I've found I can finally get a switch to appear.

In .items, I created a group and assigned the Plum switch to that group. Then it would appear. That seems to be the only reliable way to have switches appear in the browser's interface.

For example, in .items:
Group	gAll	"My House"
Group	gFloorBasement		"Basement"			<cellar>		(gAll)
Group	gBA_Family_Room		"Family Room"		<cellar>	(gFloorBasement)
Switch Light_Plum_Family_Room_Sitting_Area_Switch "Plum Family Room Sitting Area Switch" (gBA_Family_Room) {plum="LOCAL_IP:LOGICAL_LOAD#switch"}

and in .sitemap:
Frame label="Floor Plan" {
		Group item=gFloorBasement {
			Group item=gBA_Family_Room
		}		
	}

However, I cannot get a switch to appear reliably by listing it in the .sitemap.

Hope this helps someone.

**Comment by mikenemat** [comment]
Hey sorry for the late reply. Sitemap issues are generally unrelated to the source (Plum, Hue, Insteon, etc). Like you said, they show up fine in the log file.

I think your issue is the way the Switch was being configured in the site map.

Unfortunately, this is incorrect:
Switch Plum_Kitchen_Island_Switch 

It needs to be:
Switch **item=**Plum_Kitchen_Island_Switch

Let me know if that works! OpenHAB is such a pain :)

**Comment by robertjackson17** [comment]
Of course you're right Mike. Thank you. Obviously I was spent far too long yesterday staring at the code. But my mistake forced me to learn a bit more setting up OpenHAB

Perhaps you could/should add this sitemap example to the readme file so someone doesn't repeat my mistake?

Thank you for all your work in putting this binding together.

Rob

**Comment by mikenemat** [comment]
Sure Rob I'd be happy to do that. Glad it's working.
