### ISSUE TITLE
Plum Binding Not Loading?

### ISSUE THREAD

**Issue by robertjackson17** [mikenemat/org.openhab.binding.plum#2]
Hello,

While I had the binding working a week ago, I can't get it working now.

I did a reinstall of Jessie on RPi3. Therefore, I did a new install of OpenHab 1.8.2. Plum and Hue are the two bindings I'm starting with. Hue loads and controls lights. I can't get Plum working despite having the same set-up (.cfg, .items, and .sitemap) as I had when it was working.

Plum does not appear in the log file, even when setting the level to DEBUG or TRACE.

Any thoughts? Thanks.

Rob
robertjackson17@gmail.com

**Comment by mikenemat** [comment]
Hi Rob,

A couple of things:

1) Can you confirm that the JAR file org.openhab.binding.plum-1.8.2-SNAPSHOT.jar is located in /usr/share/openhab/addons/

Can you also do an ls -al on that folder and ensure it has the same permissions as the other addons?

2) Can you confirm that plum:refresh and plum:house_token are both defined in the openhab cfg?

3) Is " [INFO ] [hab.binding.plum.PlumActivator] - Plum binding has been started." showing up in the log file at all?

I'm really not sure what could have gone wrong but hopefully we can figure it out!

**Comment by robertjackson17** [comment]
Hi Mike,

1) Yes. The binding, with the filename you give, is in the /addons/ folder. In my installation, this is /opt/openhab/addons/. This is the same folder as last week when the Plum binding was working. The Hue binding is in this folder and is working. Only other bindings are http and nap, along with the exec, logging, and rrd4j persistences.

Permissions and owner on all files in this folder at the same:
-rw-r--r-- 1 root root

2) Yes. refresh and house_token are both defined in the openhab.cfg file. I've double-checked the house token against the output of plum-probe.

3) No. There are no Plum-related items showing up in the log.

As we know, it was loading a week ago. I ran into trouble getting z-wave and X10 stuff working. After little success with those two, I decided to start over. I'm pretty sure I followed the same installation steps  as the first time. Z-wave (Habmin, z-stick gen5 and a Mimolite) worked, but Plum didn't. So I started over again trying just Plum and Hue. Now Hue works and Plum doesn't.

One difference I can think of is the release dates of Raspbian Jessie. I think I had Plum working when I started with a March release which I updated on about May 7th or 8th. This time, I started with the 2016-05-10-raspbian-jessie.img. Perhaps something in the May 10th release broke the Plum binding (but not the Hue binding)?

Let me know what you'd like me to poke around at so we can figure it out.

Thanks.

**Comment by mikenemat** [comment]
Interesting. There's nothing in the Plum binding that's OS dependent...or at least there shouldn't be. If the Hue binding loads, the Plum binding should load. My OpenHAB understanding isn't particularly good, but I'll see if I can help.

1) I know this is a huge stretch but can you take a sha1 of the jar with sha1sum? It should be f7313c2603c1410805e0c3b2fcb1372f4786a221

2) Apparently there's a build of OpenHAB floating around that uses a bindings.list file in the configurations folder, and you have to define bindings in there in addition to putting the jar file in the addons folder. Can you confirm that this file doesn't exist on your machine? If it does, try to put the plum binding name in there.

**Comment by robertjackson17** [comment]
You solved it.

1) The sha1 was different. More on that below.

2) I haven't seen a bindings.list in the configuration folder. What's in that folder is the stuff directly from the OpenHab download page (with the demo).

I had moved the plum .jar file directly from github to the addons directory using
wget https://github.com/mikenemat/org.openhab.binding.plum/blob/master/target/org.openhab.binding.plum-1.8.2-SNAPSHOT.jar (the address comes from right-clicking the .jar file). That gave me a different sha1. Seems that's not the way to do it. Seems I really should figure out github.

I just downloaded the file directly to my Mac. The sha1 was correct on the Mac. I uploaded to the addons directory. Again, the sha1 was correct.

Rebooted the RPi and everything works.

Thank you (again).

**Comment by mikenemat** [comment]
Yeah that wget will download the HTML. If you want to do it with wget, you need to copy the URL from the raw button, which is:

https://github.com/mikenemat/org.openhab.binding.plum/raw/master/target/org.openhab.binding.plum-1.8.2-SNAPSHOT.jar

Enjoy!
