### ISSUE TITLE
Possible deadlock in OpenHAB 2.2

### ISSUE THREAD

**Issue by mikenemat** [mikenemat/org.openhab.binding.plum#6]
I've observed some strange issues in OpenHAB 2.2 which did not exist in OpenHAB 2.1. The plugin's main thread appears to lock for some foreseen reason after 24-48 hours, preventing polling and commands from being sent. Real-time statuses are still received and handled.

Very strange, since there is aggressive exception handling and timeouts in all of those areas.

I'm investigating.

**Comment by mikenemat** [comment]
Hey guys - found the problem. 

 EventAdmin: Blacklisting ServiceReference [{org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService}={event.topics=openhab/command/*, service.pid=org.openhab.plum, component.name=org.openhab.binding.plum.activebinding, component.id=15, service.id=354, service.bundleid=16, service.scope=bundle} | Bundle(org.openhab.binding.plum_1.11.0.201712130420 [16])] due to timeout!


Turns out this is an overly aggressive timeout bug in OpenHAB 2.2, fixed as build #1103 (though not in the release 2.2 build). This should be fixed in the next OpenHAB release, but in the mean time you can add the following to {$OPENHAB2}/etc/org.apache.felix.eventadmin.impl.EventAdmin.cfg

org.apache.felix.eventadmin.Timeout=0

*Some* bindings are unaffected by this issue because of how rapidly they execute, but there are plenty of others reporting issues with things like Wemo and MQTT. A lot of wifi-related bindings can take a bit longer to execute, and perhaps even hang for a second or two if a device has dropped off the network. The plum binding for example allows for a timeout of up to 2 seconds. Making this more aggressive on my end is an option, but I'm glad everyone has agreed that the solution is not to evict the OSGI bundle (disable the binding) until OpenHAB is restarted.

**Comment by mikenemat** [comment]
Another note, on my install, I found the config file in two locations so I updated them both, neither were the location specified above which I found on the openhab github:

userdata/config/org/apache/felix/eventadmin/impl/EventAdmin.config
userdata/etc/org.apache.felix.eventadmin.impl.EventAdmin.cfg

**Comment by mikenemat** [comment]
Reference to OpenHAB github fix:

https://github.com/openhab/openhab-distro/commit/ece645ee77e9d20f39475faadcf39ee761c783b3#diff-810265f177453673dd72f3b227073231

**Comment by billmans** [comment]
Hi Mike,

Doing some cleanup on openHAB and my plum lightpads have stopped working.  Looks like a similar issue to this, I can read power /on/off status, but can't control them at all?  I am running 2.4  1412.

Checked the settings you reference and they are as you suggested already.

Thought I would check and see if yours are still working, might just upgrade to the latest build to see if that helps!

BTW: do you know if plum (the company) is dead?  Have not heard a thing from them in a while?

Bill

**Comment by mikenemat** [comment]
Hey Bill. Plum is indeed dead. I've seen a few stories of folks being unable to provision new lightpads they purchased as spares. Scary stuff - I have some spares too. Over the next few years, I will likely replace all of mine with Lutron Caseta, Insteon, or perhaps even z-wave. I'm done with any smarthome gear that depends on wifi or the cloud for basic functionality. All in all, I think I'll be out about $1500. Lesson learned :)

Now, more importantly... Would you be able to send me some openhab logs that show an error with the plum binding? Mine are still working fine! I'm able to control them without issue.

I did see some reports on the openhab forums about some SSL issues with the plum binding, but I had a hard time replicating the issue and I began to suspect that the person might have had an issue with their OS or OpenHAB Install.

If you can get me some error logs I can dig deeper. I'm on OpenHAB 2.4 as well.

**Comment by salanki** [comment]
Wow, I must have missed that they shut down. That's a same, great technology in that package that never  got utilized. I've spent $2k in plum lightpads for my entire house, ugh.

**Comment by dome2048** [comment]
I suspect I’m the user on the forum you are referring to. Am I correct in understanding you couldn’t replicate my issue even with a fresh install of openHAB? I’ve been wracking my brain and can’t figure out much that’s different with my new installation, particularly since my openHAB is containerized. 

It really is too bad they shut down. Easily the best looking smart light switch around.

**Comment by billmans** [comment]
Hi Mike,

Thanks for the response! I feared Plum might be on the verge of
disappearing, but did not know for sure.  Its too bad, I think they had a
lot of potential, would be nice if they open-sourced any api etc or at
least let us know what would happen once the server goes down, hope they
don't stop working all together.  I will reach out to Glen as I had a
dialog with him at one point, but if he has moved on there might not be
anything left to do.

As for my issue, I have not seen any errors in the log, but I will look
closer and see what I can find for you.

As always, thanks for looking into this for me.

Bill

**Comment by billmans** [comment]
Hi Mike

Played a little today - updated to 2.5 and still not able to control plum.

I am seeing this in the log, any thoughts?

Thanks
Bill

ed from 168 to 169
11:00:51.201 [ERROR] [penhab.binding.plum.PlumActiveBinding] - Plum HTTP
Request to IP 10.0.1.36 returned ERROR javax.net.ssl.SSLException: Received
fatal alert: insufficient_security
11:00:51.229 [ERROR] [penhab.binding.plum.PlumActiveBinding] - Plum HTTP
Request to IP 10.0.1.27 returned ERROR javax.net.ssl.SSLException: Received
fatal alert: insufficient_security
11:00:51.307 [ERROR] [penhab.binding.plum.PlumActiveBinding] - Plum HTTP
Request to IP 10.0.1.26 returned ERROR javax.net.ssl.SSLException: Received
fatal alert: insufficient_security
11:00:51.334 [ERROR] [penhab.binding.plum.PlumActiveBinding] - Plum HTTP
Request to IP 10.0.1.25 returned ERROR javax.net.ssl.SSLException: Received
fatal alert: insufficient_security
11:00:51.409 [ERROR] [penhab.binding.plum.PlumActiveBinding] - Plum HTTP
Request to IP 10.0.1.32 returned ERROR javax.net.ssl.SSLException: Received
fatal alert: insufficient_security
11:00:51.436 [ERROR] [penhab.binding.plum.PlumActiveBinding] - Plum HTTP
Request to IP 10.0.1.31 returned ERROR javax.net.ssl.SSLException: Received
fatal alert: insufficient_security
11:00:51.466 [ERROR] [penhab.binding.plum.PlumActiveBinding] - Plum HTTP
Request to IP 10.0.1.28 returned ERROR javax.net.ssl.SSLException: Received
fatal alert: insufficient_security

**Comment by mikenemat** [comment]
Hey bill. Thanks for the log. I might have a chance to take a look this week. Been crazy busy lately. I’ll let you know. Just to confirm, I am not seeing this issue at all in my setup. I’ll have to do some research on it.

**Comment by mikenemat** [comment]
Hi @billmans . Can you post what version of Java you're running?  The command "java -version" should work.

**Comment by mikenemat** [comment]
FWIW, my Java version which is working fine is OpenJDK 1.8.0_191. I realize this is outdated but I'm relatively sure that this is still the recommended version for OpenHAB

$# java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by mikenemat** [comment]
Lets move discussions here: https://github.com/mikenemat/org.openhab.binding.plum/issues/7

#7
